export const ADD_PERSON_PLUS = 'ADD_PERSON_PLUS';
export const ADD_PERSON_MINUS = 'ADD_PERSON_MINUS';
export const REMOVE_PERSON_PLUS = 'REMOVE_PERSON_PLUS';
export const REMOVE_PERSON_MINUS = 'REMOVE_PERSON_MINUS';